### ISSUE TITLE
MacOS下用源码编译的，但好像没法获取数据了

### ISSUE THREAD

**Issue by honhosing** [xfgryujk/blivechat#1]
`python3 main.py -....` 之后，用浏览器打开相应的端口页面，再输入房间ID，但结果是空白一片。命令行中出现断线重连的信息：`WARNING [blivedm.blivedm]: room xxxx 掉线重连中1`

**Comment by xfgryujk** [comment]
¿我这边试没问题，要不你调试看看是什么错误

**Comment by honhosing** [comment]
> ¿我这边试没问题，要不你调试看看是什么错误

需要在main.py或者blivedm.py里加入什么参数吗？类似爬虫时添加headers、Cookie之类的。还是说像Readme.md里写的那样，直接安装完所有依赖库之后，直接python3 main.py即可？

**Comment by xfgryujk** [comment]
> > ¿我这边试没问题，要不你调试看看是什么错误
> 
> 需要在main.py或者blivedm.py里加入什么参数吗？类似爬虫时添加headers、Cookie之类的。还是说像Readme.md里写的那样，直接安装完所有依赖库之后，直接python3 main.py即可？

装完依赖直接运行就行

**Comment by honhosing** [comment]
![image](https://user-images.githubusercontent.com/18226870/59159425-0ada9680-8afc-11e9-88be-6340e8d2b317.png)

![image](https://user-images.githubusercontent.com/18226870/59159429-1ded6680-8afc-11e9-94db-043e6e2be10f.png)

重新下载源码，再安装依赖还是不行。这是运行情况（以房间号526为例）

**Comment by xfgryujk** [comment]
你下断点调试看是什么错误啊
![room526](https://user-images.githubusercontent.com/8419596/59159976-7c6a1300-8b03-11e9-9e5f-13c9cf3c7e17.png)

**Comment by xfgryujk** [comment]
要不你把`WEBSOCKET_URL`临时改成`wss://ks-live-dmcmt-bj6-pm-01.chat.bilibili.com/sub`

**Comment by honhosing** [comment]
> 要不你把`WEBSOCKET_URL`临时改成`wss://ks-live-dmcmt-bj6-pm-01.chat.bilibili.com/sub`

我发现是服务器端有弹幕信息推过来的时候，就会出现`2019-06-09 23:17:44 WARNING [blivedm.blivedm]: room XXX 掉线重连中`的报错。Websocket之前没怎么接触过，不太清楚问题出在哪里（应该是与服务器握手成功了？）
![image](https://user-images.githubusercontent.com/18226870/59160870-a0caed00-8b0d-11e9-9683-ab83b9cee8f4.png)

**Comment by xfgryujk** [comment]
> > 要不你把`WEBSOCKET_URL`临时改成`wss://ks-live-dmcmt-bj6-pm-01.chat.bilibili.com/sub`
> 
> 我发现是服务器端有弹幕信息推过来的时候，就会出现`2019-06-09 23:17:44 WARNING [blivedm.blivedm]: room XXX 掉线重连中`的报错。Websocket之前没怎么接触过，不太清楚问题出在哪里（应该是与服务器握手成功了？）
> 
> 我在blivedm.py 的`def _message_loop(self)`下了断点，确实是当有弹幕信息推到客户端时就会在抛出错误，但不知道问题出在哪里，恳请指教
> ![image](https://user-images.githubusercontent.com/18226870/59161020-a45f7380-8b0f-11e9-9993-9a40d1e89077.png)

你在except...后面加个`as e`，这样看不出错误信息

**Comment by honhosing** [comment]
终于知道是什么报错了

```
Cannot connect to host api.bilibili.com:443 ssl:None [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)]
```

**Comment by xfgryujk** [comment]
> 终于知道是什么报错了
> 
> ```
> Cannot connect to host api.bilibili.com:443 ssl:None [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)]
> ```

[这里](https://github.com/xfgryujk/blivechat/blob/82bfb69a0a25bc654e296fbd1b472cc23db02b5c/chat.py#L51)加个参数`ssl=False`

**Comment by xfgryujk** [comment]
> 终于知道是什么报错了
> 
> ```
> Cannot connect to host api.bilibili.com:443 ssl:None [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)]
> ```

[这里](https://github.com/xfgryujk/blivechat/blob/82bfb69a0a25bc654e296fbd1b472cc23db02b5c/chat.py#L32)加个参数`ssl=False`

**Comment by honhosing** [comment]
> > 终于知道是什么报错了
> > ```
> > Cannot connect to host api.bilibili.com:443 ssl:None [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)]
> > ```
> 
> [这里](https://github.com/xfgryujk/blivechat/blob/82bfb69a0a25bc654e296fbd1b472cc23db02b5c/chat.py#L51)加个参数`ssl=False`

还是一样的报错信息。我查了一下，有个[帖子](https://blog.csdn.net/yuezhuo_752/article/details/84375733)说在脚本里添加
```
import ssl
ws.run_forever(sslopt={"cert_reqs": ssl.CERT_NONE})
```
不过我看blivedm.py里的websocket构造方法不是直接import websocket，试了一下在这个地方加了进去
![image](https://user-images.githubusercontent.com/18226870/59161343-336e8a80-8b14-11e9-9335-4d7f7666f82c.png)

虽然是没有抛出异常，但还是没有接收到弹幕信息

**Comment by xfgryujk** [comment]
不是websocket的问题，那个错误是获取头像时api.bilibili.com证书不对的问题，我上面的链接改了

**Comment by honhosing** [comment]
> 不是websocket的问题，那个错误是获取头像时api.bilibili.com证书不对的问题，我上面的链接改了

万分感谢！终于接收到弹幕信息了！
