### ISSUE TITLE
自定义表情添加过多时OBS无法加载URL

### ISSUE THREAD

**Issue by FutabaWasuke** [xfgryujk/blivechat#107]
bilivechat 1.61版本
OBS 29.0.2 便携版

当我添加了超多的自定义表情的时候，疑似URL太长无法被OBS加载。链接如下：

`https://xfgryujk.sinacloud.net/blivechat/loader.html?url=http%3A%2F%2Flocalhost%3A12450%2Froom%2F30077794%3FminGiftPrice%3D7%26showDanmaku%3Dtrue%26showGift%3Dtrue%26showGiftName%3Dfalse%26mergeSimilarDanmaku%3Dfalse%26mergeGift%3Dtrue%26maxNumber%3D60%26blockGiftDanmaku%3Dtrue%26blockLevel%3D0%26blockNewbie%3Dfalse%26blockNotMobileVerified%3Dfalse%26blockKeywords%3D%25E7%2582%25B9%25E6%25AD%258C%250A%25E6%25AC%25A2%25E8%25BF%258E%26blockUsers%3D%26blockMedalLevel%3D0%26relayMessagesByServer%3Dfalse%26autoTranslate%3Dfalse%26giftUsernamePronunciation%3D%26emoticons%3D%255B%257B%2522keyword%2522%253A%2522%255Bdog%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252F585af6fd3d79758dcd976b59ac19bf3b.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%25E8%25BD%25BB%25E5%259E%258B%25E7%25AA%2581%25E5%2587%25BB%25E5%2585%25B5%2522%2C%2522url%2522%253A%2522%252Femoticons%252Fce98f41ecee01d52aee059cb2316b2d6.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%25E9%2587%258D%25E5%259E%258B%25E7%25AA%2581%25E5%2587%25BB%25E5%2585%25B5%2522%2C%2522url%2522%253A%2522%252Femoticons%252F5cae0e6957e2544fe84ac4eacea717a5.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%25E5%25B7%25A5%25E7%25A8%258B%25E5%2585%25B5%2522%2C%2522url%2522%253A%2522%252Femoticons%252Fd5f3898c90cdd201b47b0fdd0af05080.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%25E6%2588%2598%25E6%2596%2597%25E5%258C%25BB%25E7%2596%2597%25E5%2585%25B5%2522%2C%2522url%2522%253A%2522%252Femoticons%252F391d10edb303b0c71fc6dbab6ae82190.png%2522%257D%2C%257B%2522keyword%2522%253A%2522MAX%2522%2C%2522url%2522%253A%2522%252Femoticons%252Ff38d80592462315f190753092df27ac1.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%25E6%25B8%2597%25E9%2580%258F%25E8%2580%2585%2522%2C%2522url%2522%253A%2522%252Femoticons%252Fd91415c2550a9d4afc81fa5497edaf19.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E5%25BE%25AE%25E7%25AC%2591%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252F289dab6c01c550264c8d8ce158cec985.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E5%2593%25A6%25E5%2591%25BC%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252Ff6ab3d9852767756e7a0473c0aa07ae4.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E7%2596%2591%25E6%2583%2591%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252Fa058d5b07d22062f87961a3748831713.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E8%25BE%25A3%25E7%259C%25BC%25E7%259D%259B%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252Fe745cabe64ec3f9d5cb80a61bf710377.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E5%25A5%25B8%25E7%25AC%2591%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252Fd1b34c86063e08010c218fa2b2006399.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E9%2598%25B4%25E9%2599%25A9%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252F1f36177ff9d589e9036f39bc3cfa2473.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E5%259B%25A7%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252Fa8ac5c4d0ca6adbe196121d1ffde9039.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E6%258A%25A0%25E9%25BC%25BB%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252F3df400e6cb39727daca7fa50a14acb1b.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E7%25AC%2591%25E5%2593%25AD%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252F72a7f24c80654b4c2c49d740f008c0a7.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E7%2582%25B9%25E8%25B5%259E%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252F148a5786e3fd831b20fa2da1dfee31aa.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E5%25B0%25B4%25E5%25B0%25AC%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252F02d9cee462e12fdfbe9f877525708d43.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E5%2582%25B2%25E5%25A8%2587%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252F0b332730757fefb5cb06a2239a7931ca.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E7%2596%25BC%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252F44f98b3f51c104646497b4bde3ca49ae.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E5%25A5%258B%25E6%2596%2597%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252F631b7f71886fafba61665329f524ae63.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E9%2594%25A6%25E9%25B2%25A4%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252Fe02a3c4121a6b75e7f9b4154ad16d85e.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E6%258A%25B1%25E6%258B%25B3%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252F00c03b4c150a4818b288cb9d8ce5dd35.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E5%2593%258D%25E6%258C%2587%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252F36fb64307215ba2edb00ab2de6cc8850.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E9%25BB%2591%25E6%25B4%259E%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252F6a3d5cc66eb1c2986c90c36908e763d7.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B2020%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252F7a5a9a24d687b74f5f2cfefe0729b2e8.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E7%25A6%258F%25E5%2588%25B0%25E4%25BA%2586%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252F06c26363d04e9559ddfdfd63e171ee2f.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E9%25AB%2598%25E5%2585%25B4%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252F444f9bc29fd04d000868112a6ca1057b.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E6%25B0%2594%25E6%2584%25A4%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252F4fd5e91964631b19dfa053b895b33a88.png%2522%257D%2C%257B%2522keyword%2522%253A%2522%255B%25E8%2580%258D%25E5%25B8%2585%255D%2522%2C%2522url%2522%253A%2522%252Femoticons%252F446fd9326e944c4efaf1adcdf587ef85.png%2522%257D%2C%257B%2522keyword%2522%253A%2522wrel%2522%2C%2522url%2522%253A%2522%252Femoticons%252F6d95b385d806312a2e15c19c91285237.png%2522%257D%255D%26lang%3Dzh`

**Comment by xfgryujk** [comment]
已知，但是不想把配置存到服务器上，只能放到URL了

**Comment by xfgryujk** [comment]
现在可以在后端配置自定义表情了，刚好可以解决这个，不过会给所有用户生效
