### ISSUE TITLE
运行blivechat后无法打开Windows11系统设置

### ISSUE THREAD

**Issue by J-Zhang99** [xfgryujk/blivechat#108]
[blivechat issue.txt](https://github.com/xfgryujk/blivechat/files/11784304/blivechat.issue.txt)
![image](https://github.com/xfgryujk/blivechat/assets/56030405/71817ada-14e1-445a-8b44-4d9a806ca42c)
blivechat的报错信息和系统设置截图如附件所示。

**Comment by Xeler-ync** [comment]
老哥你图没截好
这给问题是之前头像的问题  #84

**Comment by xfgryujk** [comment]
还是头像接口的问题，和系统设置没关系
