### ISSUE TITLE
SuperChat功能意見

### ISSUE THREAD

**Issue by yfk2012** [xfgryujk/blivechat#11]
想知道這個項目會不會繼續更新?
未來會不會有類似真正的SuperChat功能?
例如 可以讓DD們投餵金瓜子或者上艦後一定秒數內(可以自定義時長?)可以輸入 $ xxxxx 取代原本Sent 小電視飛船x1
並且可以置頂一定時間(可以自定義?)

**Comment by xfgryujk** [comment]
SC功能准备制作了#10 
置顶的话现在已经有了，和YouTube的一致，可以通过样式开启和关闭
