### ISSUE TITLE
1.6.2版本无法获取头像和用户名

### ISSUE THREAD

**Issue by ITManCHINA** [xfgryujk/blivechat#115]
似乎是[Wbi鉴权](https://socialsisteryi.github.io/bilibili-API-collect/docs/misc/sign/wbi.html#wbi%E7%AD%BE%E5%90%8D%E7%AE%97%E6%B3%95)相关导致的，5分钟后无法展示头像和完整昵称

![bug演示](https://s2.loli.net/2023/07/17/jEluwKktSRfnDaQ.png)

**Comment by xfgryujk** [comment]
我看了几个人都是正常的。前端直连的话可能要刷新OBS的浏览器
