### ISSUE TITLE
无法显示基础表情

### ISSUE THREAD

**Issue by Jiematcha** [xfgryujk/blivechat#117]
[](url)
<img width="120" alt="屏幕截图 2023-07-22 141156" src="https://github.com/xfgryujk/blivechat/assets/34316465/3761c064-9d71-40e6-a6c6-3600d38631ad">

**Comment by Jiematcha** [comment]
基础表情是不是被识别为文字，只能自己映射？

**Comment by xfgryujk** [comment]
暂时没做这个功能

**Comment by xfgryujk** [comment]
duplicate of #97
