### ISSUE TITLE
获取不到弹幕，能不能帮忙看看，按教程设置了但是不行

### ISSUE THREAD

**Issue by GitHubKumasang** [xfgryujk/blivechat#121]
之前都可以但是更新1.7之后就不可以了，联系方式qq393458814，有时候会显示nonetype
![微信图片_20230903114554](https://github.com/xfgryujk/blivechat/assets/97335538/679ff412-6788-46b8-b290-47e4e1ad82d4)

**Comment by xfgryujk** [comment]
最近B站的风控策略又改了，未登录用户获取弹幕时可能会被严重限流，可能是这个原因

**Comment by FangDingli** [comment]
今天确实看见几个主播都遇到了这问题  弹幕获取频率很低

**Comment by GitHubKumasang** [comment]
这样啊，我说呢，我还以为是我改了hosts的问题，折磨我两天了QAQ

**Comment by flywolf53** [comment]
> 最近B站的风控策略又改了，未登录用户获取弹幕时可能会被严重限流，可能是这个原因
目前有什么应急对策方法吗？

**Comment by xfgryujk** [comment]
> > 最近B站的风控策略又改了，未登录用户获取弹幕时可能会被严重限流，可能是这个原因
>
> 目前有什么应急对策方法吗？

立即解决的方法没有，或者你可以自己改代码加上cookie和uid。等我接入官方的开放平台吧，快的话这周能做完

**Comment by yanjisheng** [comment]
> > > 最近B站的风控策略又改了，未登录用户获取弹幕时可能会被严重限流，可能是这个原因
> > 
> > 
> > 目前有什么应急对策方法吗？
> 
> 立即解决的方法没有，或者你可以自己改代码加上cookie和uid。等我接入官方的开放平台吧，快的话这周能做完

这个接入官方开放平台只要你接入就行吗，还是每个用户都要接入呢，需要如何操作呢

**Comment by xfgryujk** [comment]
> > > > 最近B站的风控策略又改了，未登录用户获取弹幕时可能会被严重限流，可能是这个原因
> > > 
> > > 
> > > 目前有什么应急对策方法吗？
> > 
> > 
> > 立即解决的方法没有，或者你可以自己改代码加上cookie和uid。等我接入官方的开放平台吧，快的话这周能做完
> 
> 这个接入官方开放平台只要你接入就行吗，还是每个用户都要接入呢，需要如何操作呢

Read The ~~Fucking~~ Fine Documentation: https://open-live.bilibili.com/document/849b924b-b421-8586-3e5e-765a72ec3840
