### ISSUE TITLE
除了开放平台之外，弹幕连接是否有支持Cookie的计划

### ISSUE THREAD

**Issue by hguandl** [xfgryujk/blivechat#124]
经过测试，只需要获取 buvid 和 SESSDATA 即可以用户身份连接弹幕。对于代码的修改量较少，只需在请求里添加 Cookie，并在 config 文件里添加对应项目。有计划的话，我可以PR一份我的实现。

**Comment by xfgryujk** [comment]
没有这个计划了，和反爬虫干太费头发
