### ISSUE TITLE
头像和名字都直接*号了，求助

### ISSUE THREAD

**Issue by sfmoting** [xfgryujk/blivechat#125]
求助，我按照配置教程配置了，但是头像和名字都直接*号了，我也试了其他人电脑也是一样

**Comment by sfmoting** [comment]
哈哈哈，加油

**Comment by sfmoting** [comment]
> 你先别急，让我先急

哈哈哈加油

**Comment by cirfi** [comment]
好像 blivedm 通过身份码获取的弹幕都没啥问题的样子，不太清楚这个身份码有没有影响大不大。
