### ISSUE TITLE
新版是否只能在本地使用无法挂服务器？

### ISSUE THREAD

**Issue by xiaobaozi233** [xfgryujk/blivechat#129]
测试的时候发现生成的https://xfgryujk.sinacloud.net/xxx网址只能在部署服务器打开，obs推流主机输入这个网址是无法显示。

跳转成http://localhost:12450/room/后手动更换成部署的域名可以正常使用。

**Comment by xfgryujk** [comment]
https://github.com/xfgryujk/blivechat/blob/b5c75543650fd53c782b6b8df2c31cf0f796b75c/README.md?plain=1#L105-L107

Read The ~Fucking~ Friendly Manual

**Comment by xiaobaozi233** [comment]
傻逼了，看的还是老的配置文件
