### ISSUE TITLE
v1.8.0启动失败

### ISSUE THREAD

**Issue by LiXDL** [xfgryujk/blivechat#130]
- 系统：Windows 11
- 行为：双击`blivechat.exe`启动后自动退出
- 通过CMD运行后显示如下报错
![image](https://github.com/xfgryujk/blivechat/assets/38141753/8e460231-8dc6-4496-99e8-07a3a6ffec8e)

netstat看了一下12450端口也没有被占用，救救

**Comment by xfgryujk** [comment]
你从源代码运行，把这里的except删掉，看看是什么错误
https://github.com/xfgryujk/blivechat/blob/63ef4ac97183f02f88a2aa97515e3d0c19d5a7cc/main.py#L138

**Comment by LiXDL** [comment]
![2ZF0)Q}QF0@2IAA%J%}UBDU](https://github.com/xfgryujk/blivechat/assets/38141753/5e969916-6837-4f19-b9c5-da453990e48c)
↑长这样

**Comment by xfgryujk** [comment]
感觉还是端口占用了，你换个端口或者重启系统呢

**Comment by LiXDL** [comment]
还真是，重启了一下就好了
非常感谢
