### ISSUE TITLE
[v1.8.0] 使用身份码时，房管样式无法正常显示

### ISSUE THREAD

**Issue by zyh310** [xfgryujk/blivechat#131]
经对比测试，同样使用“仿微信”预设CSS样式：
+ 使用**身份码**时，房管背景颜色为**白色**
+ 使用**房间号**时，房管背景颜色为**蓝色**

舰长、主播样式均正常。

**Comment by xfgryujk** [comment]
没办法，开放平台接口不会告诉你用户是不是房管，他们也没打算加

**Comment by Chenguoz** [comment]
- 使用房间号时，房管背景颜色为蓝色，但名称加载不全
- 使用身份码时，名称正常加载，但房管背景颜色为白色

maybe这两可以合并一下:)

**Comment by DoodleBears** [comment]
身份码（接入B站开放平台），对应的开放平台API没有提供（是否是房管）数据。这个 issue 之前提过了吧

2023-10-02 16:53 GMT+09:00, Chenguo ***@***.***>:

**Comment by xfgryujk** [comment]
> * 使用房间号时，房管背景颜色为蓝色，但名称加载不全
> * 使用身份码时，名称正常加载，但房管背景颜色为白色
> 
> maybe这两可以合并一下:)

别折磨我了
