### ISSUE TITLE
1.8.0用户名显示有问题

### ISSUE THREAD

**Issue by StupidCatVix** [xfgryujk/blivechat#132]
为什么所有用户名都只显示第一个字后面全是星号qwq
而且也不能分辨用户的身份是主播还是观众还是什么

**Comment by StupidCatVix** [comment]
我已经用了身份码但是就是不行

**Comment by xfgryujk** [comment]
你改了配置房间URL会变，OBS里的URL也要改啊

**Comment by StupidCatVix** [comment]
已经改过了

**Comment by StupidCatVix** [comment]
> 你改了配置房间URL会变，OBS里的URL也要改啊

改过了xwx

**Comment by xfgryujk** [comment]
能贴一下URL吗，我试过之后你刷新一下身份码

**Comment by StupidCatVix** [comment]
> 能贴一下URL吗，我试过之后你刷新一下身份码

我正在用xwx

**Comment by StupidCatVix** [comment]
> 能贴一下URL吗，我试过之后你刷新一下身份码

https://xfgryujk.sinacloud.net/blivechat/loader.html?url=http%3A%2F%2Flocalhost%3A12450%2Froom%2FCXSLRG76OKJK6%3FminGiftPrice%3D0%26showDanmaku%3Dtrue%26showGift%3Dtrue%26showGiftName%3Dtrue%26mergeSimilarDanmaku%3Dfalse%26mergeGift%3Dtrue%26maxNumber%3D60%26blockGiftDanmaku%3Dfalse%26blockLevel%3D0%26blockNewbie%3Dfalse%26blockNotMobileVerified%3Dfalse%26blockKeywords%3D%26blockUsers%3D%26blockMedalLevel%3D0%26relayMessagesByServer%3Dtrue%26autoTranslate%3Dfalse%26giftUsernamePronunciation%3D%26emoticons%3D%255B%255D%26roomKeyType%3D2%26lang%3Dzh

**Comment by xfgryujk** [comment]
在我这里好好的，一定是你OBS里URL错了

![QQ截图20230916235242](https://github.com/xfgryujk/blivechat/assets/8419596/a286f340-c439-4e30-8c97-314aa05ce978)

**Comment by StupidCatVix** [comment]
> 在我这里好好的，一定是你OBS里URL错了
> 
> ![QQ截图20230916235242](https://user-images.githubusercontent.com/8419596/268457553-a286f340-c439-4e30-8c97-314aa05ce978.png)

没啊我粘贴进去的

**Comment by xfgryujk** [comment]
要不你把所有的浏览器源删掉再重新添加

**Comment by Xeler-ync** [comment]
开平的一个身份码好像只能同时给一个用，你勾一下obs里面的不可见时关闭源或者用服务端转发应该就可以了

**Comment by StupidCatVix** [comment]
> 开平的一个身份码好像只能同时给一个用，你勾一下obs里面的不可见时关闭源或者用服务端转发应该就可以了

都开了

**Comment by Natsumerem** [comment]
请问海外用户日语环境弹幕栏里的用户名都只有第一个字后面都是*号  是可能什么问题引起的？
 例如：“极***”

**Comment by xfgryujk** [comment]
> 请问海外用户日语环境弹幕栏里的用户名都只有第一个字后面都是_号 是可能什么问题引起的？ 例如：“极_**”

需要升级到1.8之后，用身份码连接房间
