### ISSUE TITLE
Docker 实际版本是否还停留在v1.7.0

### ISSUE THREAD

**Issue by Jiematcha** [xfgryujk/blivechat#133]
使用 latest 和 v1.8.1，网页依旧显示 v1.7.0

docker run --name blivechat \
  -d \
  -p 12450:12450 \
  --mount source=blivechat-data,target=/mnt/data \
  xfgryujk/blivechat:latest

**Comment by xfgryujk** [comment]
可能有缓存，Shift + F5 刷新

**Comment by Jiematcha** [comment]
> 可能有缓存，Shift + F5 刷新

无效，换浏览器也无效

**Comment by xfgryujk** [comment]
你的latest镜像可能是旧的，用v1.8.1试试
