### ISSUE TITLE
关于如何获取野生接口和类似野生接口数据的问题

### ISSUE THREAD

**Issue by skyatgit** [xfgryujk/blivechat#134]
1. 目前看来使用TCP连接的弹幕服务器使用游客登录返回的数据还是完整的，走的是2243端口（但怀疑是官方漏掉了TCP接口的限制，可能用不了多久就会和WS的游客登录一样）
2. 提供扫码登录的功能（但是可能会有风险，不太建议使用）
3. 既然本程序本身携带了一个python的后台程序，可以在用户使用了直播姬的情况下通过网卡抓包的方式直接获取直播姬的弹幕，这种方式还省去了鉴权心跳等逻辑，这里是我用C#实现的一个程序 https://github.com/skyatgit/BLivehimeNTR ，用python抓的话貌似更容易一些，然后转发给前端使用
4. 添加使用从本地服务器获取数据的选项，如上的，https://github.com/skyatgit/BLivehimeNTR 这个项目可以从直播姬获取弹幕数据，解压后转发到本地开启的WS和TCP服务器，可以在前端选择房间号还是身份码的地方加一个自定义本地服务器的选项，然后将服务器地址的值传到此处
![image](https://github.com/xfgryujk/blivechat/assets/42607334/611c8f55-4a14-4766-93e8-b57638dcc8a3)

达到如下的效果（我不懂前端的代码所以只能这样暴力修改值）其他地方的野生接口逻辑完全不用改，完美兼容
![image](https://github.com/xfgryujk/blivechat/assets/42607334/6a0a4989-6736-4e81-8d15-eaf05bc51517)
就可以正常的获取类似野生接口的数据

5. 当然如果不想使用直播姬的情况下，还有另外一个项目可以通过扫码登录的方式正常的获取直播姬弹幕数据，https://github.com/skyatgit/BLiveTransponder 它与3中所述的项目达到的效果一模一样（但是可能会有风险，不太建议使用）

**Comment by xfgryujk** [comment]
1. 我不希望再依赖其他程序，这种做法还要在本地开一个直播姬
2. 后端设计是可以多个直播间同时使用的，而直播姬只能获取一个直播间的数据
3. 将来加上传输层加密就抓不了包了。裸TCP协议应该快被B站废弃了，将来都是WSS

**Comment by skyatgit** [comment]
好
