### ISSUE TITLE
关于开发者秘钥与请求转发的问题

### ISSUE THREAD

**Issue by hekatech** [xfgryujk/blivechat#136]
看了下 B 站动态提到「如果后台配置如果没有填开发者秘钥，则会把请求转发到我的服务器」
想请问一下这个转发的请求，是仅针对身份码验证的请求，还是所有的弹幕获取请求都走公共服务器？
如果是后者的话，那么对于没有开发者秘钥也不需要自定义的一般用户来说，本地包的意义是不是就不大了呢

**Comment by xfgryujk** [comment]
仅针对身份码验证的请求，目前只有每个房间页面第一次连接时才会发到我这里

**Comment by hekatech** [comment]
> 仅针对身份码验证的请求，目前只有每个房间页面第一次连接时才会发到我这里

了解了，感谢！
