### ISSUE TITLE
添加播放gif动图功能

### ISSUE THREAD

**Issue by luzhou9510** [xfgryujk/blivechat#14]
您好，John。你所做的让我感觉到太惊喜了。没想到有人能做出像twitch直播的功能。如果方便，我也想为这个repository贡献自己的一份力量。谢谢，如果看到了请回复。

**Comment by xfgryujk** [comment]
说说你的想法吧

**Comment by luzhou9510** [comment]
你好，我也想弄一个类似这种的。但是没有啥经验，所以想学习学习。

**Comment by xfgryujk** [comment]
你说添加播放gif动图是什么意思

**Comment by luzhou9510** [comment]
就是在对话列表中那个礼物是个动图，就像现在b站上礼物在聊天窗口是动图一样。我想试试看能不能弄出来。

**Comment by luzhou9510** [comment]
你觉得如何

**Comment by xfgryujk** [comment]
可是YouTube没有礼物，只有SC

**Comment by luzhou9510** [comment]
好吧，那我可以尝试往里面添加功能吗？

**Comment by xfgryujk** [comment]
你fork一份随便改
