### ISSUE TITLE
问一下自定义表情的问题

### ISSUE THREAD

**Issue by flywolf53** [xfgryujk/blivechat#142]
在设定页面点「进入房间」，发对应文字弹幕，房间页面的弹幕可以正常转换为图片
但是在b站直播测试的时候，弹幕栏还是显示不了图片，依然是文字
不知道是不是哪里设定有误

**Comment by xfgryujk** [comment]
1. 修改配置后房间URL会变，需要重新复制
2. URL长度太长会被直播姬截断，可能会丢失自定义表情配置
