### ISSUE TITLE
[Feature Request] 用户体验：自动更新 / 包管理器兼容（优先级低）

### ISSUE THREAD

**Issue by FurryR** [xfgryujk/blivechat#144]
# 需求是？
1. 自动更新，无需手下 release。
2. 在使用 poetry/pdm 等包管理器时，git pull 不会遇到可能的冲突。
# 为什么？
1. 手动更新比较麻烦。嗯。
2. 如果我手头上有 Python 我就无需再下一个 Python 了，但用包管理器比建 venv 简单（有 IDE 另说），即使这样在当前的版本会导致再次同步时出现一些小问题。
3. 适应（或统一）贡献者环境杂乱的情况（有些人用 venv + pip，有些人用 anaconda，有些人用 poetry/pdm，有些人直接用 pip）。
# 怎么做？
（针对问题 2）将 poetry/pdm 相关文件添加到 .gitignore，或者项目使用 pdm/poetry 管理依赖&隔离环境。
# 有必要？
是的，没有做这个的必要，但是也可以做做。
# 谁问你了？
我问的。
# 自己做去！
十分抱歉，我不是很会 Python。

---

另注：虽然自觉是好的，但也有人不会遵守一定的提问格式（导致 debug 困难/理解不了需求）。为此，或许有添加 issue template 的必要，当然也可以不添加。

**Comment by xfgryujk** [comment]
没有修改已有文件的情况下，git pull怎么会冲突

**Comment by xfgryujk** [comment]
自动更新有很多要考虑的问题

1. GitHub有概率被墙
2. 打包成exe后的文件列表和直接用py文件运行不一样
3. 如果新版启动失败，是否要回滚，怎么实现
4. 如果新版和旧版数据格式不兼容，怎么迁移

这堆挺难做好的，所以一直都是手动更新，遇到问题再具体处理
