### ISSUE TITLE
公共服务器的身份码服务挂啦

### ISSUE THREAD

**Issue by FangDingli** [xfgryujk/blivechat#147]
![202311241912048](https://github.com/xfgryujk/blivechat/assets/45346648/35c689f5-3ed6-48b4-b8ac-248ca94a4378)

应该是这个的问题吧

**Comment by xfgryujk** [comment]
已知，今天开放平台给直播工具加了心跳要求，我之前没有机会充分测试，导致雪崩了。B站下架了我的应用，等我修好上架吧

**Comment by FangDingli** [comment]
好的辛苦啦

**Comment by FangDingli** [comment]
> 已知，今天开放平台给直播工具加了心跳要求，我之前没有机会充分测试，导致雪崩了。B站下架了我的应用，等我修好上架吧

好的辛苦

**Comment by ITManCHINA** [comment]
> 已知，今天开放平台给直播工具加了心跳要求，我之前没有机会充分测试，导致雪崩了。B站下架了我的应用，等我修好上架吧

正好这两天直播也遇到了这个问题，期待大佬的更新

**Comment by Crayon-ShinChan** [comment]
辛苦了！

**Comment by CoffeeSwt** [comment]
期待大佬更新！

**Comment by ITManCHINA** [comment]
感谢大佬
