### ISSUE TITLE
无限报错precondition failed

### ISSUE THREAD

**Issue by 7est** [xfgryujk/blivechat#149]
`Traceback (most recent call last):
  File "/home/wwwroot/lnmp01/domain/chat/web/api/open_live.py", line 101, in _request_open_live
    return await _read_response(req_ctx_mgr)
  File "/home/wwwroot/lnmp01/domain/chat/web/api/open_live.py", line 122, in _read_response
    raise TransportError(f'{type(e).__name__}: {e}')
api.open_live.TransportError: ClientResponseError: 412, message='Precondition Failed', url=URL('https://live-open.biliapi.com/v2/app/start')
2023-12-01 23:09:00,275 ERROR [tornado.access]: 500 POST /api/open_live/start_game (127.0.0.1) 41.26ms`

**Comment by xfgryujk** [comment]
你被B站风控ban了

**Comment by 7est** [comment]
> 你被B站风控ban了

最近确实被很多人恶意使用了，大概等一个星期能好吗

**Comment by xfgryujk** [comment]
> > 你被B站风控ban了
> 
> 最近确实被很多人恶意使用了，大概等一个星期能好吗

不知道，我还是找B站人员提工单才解的。如果很多人用的话最好更新到batch_heartbeat分支的最新版本，添加了批量心跳和请求限流，应该不会被ban了

**Comment by 7est** [comment]
> > > 你被B站风控ban了
> > 
> > 
> > 最近确实被很多人恶意使用了，大概等一个星期能好吗
> 
> 不知道，我还是找B站人员提工单才解的。如果很多人用的话最好更新到batch_heartbeat分支的最新版本，添加了批量心跳和请求限流，应该不会被ban了

感谢🙏

**Comment by 7est** [comment]
> > > 你被B站风控ban了
> > 
> > 
> > 最近确实被很多人恶意使用了，大概等一个星期能好吗
> 
> 多少个人用？我服务器也挺多人用的

没看具体的，每时每刻都有推送到我手机上的预警，因为被风控了所以用户会连接失败，无限请求，导致短时间内多次朝着一个地址请求触发了预警推送
