### ISSUE TITLE
[BUG]1.8.2版本启动时概率闪退

### ISSUE THREAD

**Issue by UnrealOfficial** [xfgryujk/blivechat#159]
用了也挺久了，至少每个月有那么1-2天会闪退，在线版不知为啥会给用户名打码
![image](https://github.com/xfgryujk/blivechat/assets/105903609/508e0551-78bc-4081-a29b-6ce2e4d317d8)

**Comment by xfgryujk** [comment]
看一下日志或者控制台有报错吗
