### ISSUE TITLE
连接chat.bilisc.com失败

### ISSUE THREAD

**Issue by 6DDUU6** [xfgryujk/blivechat#165]
![image](https://github.com/xfgryujk/blivechat/assets/51308585/fbb4b9ab-f9f8-4105-af9e-73b5ba6bc8bb)
这个地址是固定的吗？如何修改为本地的呢

**Comment by xfgryujk** [comment]
https://github.com/xfgryujk/blivechat/blob/60efe1d55b71caedbc0d355b0ecf55e6af413e35/data/config.example.ini#L64-L68

**Comment by 6DDUU6** [comment]
> https://github.com/xfgryujk/blivechat/blob/60efe1d55b71caedbc0d355b0ecf55e6af413e35/data/config.example.ini#L64-L68

那现在这个问题怎么解决呢，只能等公共服务器好了是吧

**Comment by xfgryujk** [comment]
你不会在新疆吧

**Comment by xfgryujk** [comment]
这个表现是网站被墙了。但我看了拨测，全国应该都能连上我的服务器。你好好反思一下

**Comment by 6DDUU6** [comment]
好了好了，原来是代理的问题（）感谢

**Comment by YumeMichi** [comment]
福州电信表示也这样哈哈哈
