### ISSUE TITLE
大神们，能不能添加个功能

### ISSUE THREAD

**Issue by luzhou9510** [xfgryujk/blivechat#17]
Hi，你好。
  我是一个月前和你接触的迷弟。我是想添加个收到礼物会播放一个提前预设的gif图和录音，就像twitch平台那样。但是没搞定，所以只能求助大神们。我的想法是类似弹幕一样，有一个独立的网页，但是这个网页只是在接收到礼物会显示出来，预设一段播放时间，然后就变透明。你们觉得怎么样？

**Comment by xfgryujk** [comment]
可以用opacity和CSS3动画，音频可以用HTML5的audio，自己fork改吧

**Comment by Afanyiyu** [comment]
我做（迫真
