### ISSUE TITLE
字体Selector增加预览

### ISSUE THREAD

**Issue by ssoda01** [xfgryujk/blivechat#170]
<img width="349" alt="image" src="https://github.com/xfgryujk/blivechat/assets/96223880/b5b4fae2-9314-4bd0-a488-3495c3cd31cd">

算是字体选择增强吧，因为同时也在加点别的，正在做这些功能：
- 可以多选字体，让出的string变成"[font1],[font2]"
- 记忆输入过的自定义字体，存入localstorage。（并且可以按左边的删除按钮自己删掉。）
- 增加字体预览

但是感觉这个目前预览效果好丑，删除放左边也怪怪的

**Comment by xfgryujk** [comment]
可以，你提PR吧

**Comment by ssoda01** [comment]
有些样式修改 最新的状态截图放在pr了
