### ISSUE TITLE
屏蔽关键词请求添加正则

### ISSUE THREAD

**Issue by Naexen** [xfgryujk/blivechat#20]

**Comment by xfgryujk** [comment]
正则不是每个主播都会啊

**Comment by Naexen** [comment]
那你把屏蔽词上限调高点如何 我大概添加几十个好像就不能加新的了
或者内置一下这个屏蔽列表?
https://github.com/fighting41love/funNLP/tree/master/data/%E6%95%8F%E6%84%9F%E8%AF%8D%E5%BA%93

**Comment by xfgryujk** [comment]
屏蔽词没有上限，只是现在配置都放在URL里，想添加更多的话可以魔改
