### ISSUE TITLE
由于B站弹幕协议更新 无法正常使用

### ISSUE THREAD

**Issue by kevinluo6188** [xfgryujk/blivechat#21]
RT

**Comment by xfgryujk** [comment]
最新版本没有问题

**Comment by kevinluo6188** [comment]
？啥时候的版本




    


在2020年04月11日 22:32，John Smith 写道： 
最新版本没有问题

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/xfgryujk/blivechat/issues/21#issuecomment-612434367",
"url": "https://github.com/xfgryujk/blivechat/issues/21#issuecomment-612434367",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by xfgryujk** [comment]
3月21号，v1.4.2
