### ISSUE TITLE
报错 Failed to send open live heartbeat 

### ISSUE THREAD

**Issue by chasiopen** [xfgryujk/blivechat#213]
Failed to send open live heartbeat: AxiosError: timeout of 15000ms exceeded

使用的是网页部署方法，可以正常获取弹幕，但是隔一段时间会弹出这个报错。

![image](https://github.com/xfgryujk/blivechat/assets/35827956/7198a277-9d63-457f-b876-72862d2975ff)

**Comment by xfgryujk** [comment]
Read The Fucking Documentation

**Comment by silent404** [comment]
@xfgryujk 我读完了所有的文档，还是没有找到解决方法，我也有这个问题
I've read all the documentation and still haven't found a solution, I'm having this problem as well
![Image](https://github.com/user-attachments/assets/a58b9164-a1d0-44ca-8633-27fd92c0f03b)

**Comment by xfgryujk** [comment]
> [@xfgryujk](https://github.com/xfgryujk) 我读完了所有的文档，还是没有找到解决方法，我也有这个问题 I've read all the documentation and still haven't found a solution, I'm having this problem as well ![Image](https://github.com/user-attachments/assets/a58b9164-a1d0-44ca-8633-27fd92c0f03b)

v1.9.3已经优化过了，先升级到最新版本再说。偶尔出现这个消息不影响连接，如果还是一直超时就没办法了
