### ISSUE TITLE
[安全警告]cdn.bootcdn.net 可能被投毒, 需要替换 

### ISSUE THREAD

**Issue by jqtmviyu** [xfgryujk/blivechat#214]
安全研究人员和开源情报 (OSINT) 爱好者发现与 [polyfill.io](http://polyfill.io/) 域相关联的 GitHub 存储库涉及大规模供应链攻击，目前据信已影响了数千万个网站。
https://github.com/uBlockOrigin/uAssets/pull/24285

https://www.bleepingcomputer.com/news/security/polyfillio-bootcdn-bootcss-staticfile-attack-traced-to-1-operator/

**Comment by xfgryujk** [comment]
国内还有什么能用的CDN吗

**Comment by jqtmviyu** [comment]
> 国内还有什么能用的CDN吗

https://github.com/jqtmviyu/blivechat/commit/37bf3f483265f46220ede1fefc584af65e7fa0a5

我是换成jsdelivr+保底本地. 国内似乎只剩下个字节跳动. 奇舞挂了. 七牛云也被投了.

**Comment by xfgryujk** [comment]
我暂时打包好了
