### ISSUE TITLE
我的房管颜色呢？

### ISSUE THREAD

**Issue by UnrealOfficial** [xfgryujk/blivechat#234]
如图所示，我在该直播间内拥有房管权限，使用版本为本地版1.9.2，css里确定是已经开启了房管名称染色的
附直播间链接：https://live.bilibili.com/27843063
![image](https://github.com/user-attachments/assets/bde3fb23-0654-4b3e-8d52-fbefb0fbda6d)

![image](https://github.com/user-attachments/assets/d822643a-6a4c-4cab-9bdb-87b1f81507b2)

**Comment by xfgryujk** [comment]
官方接口不给房管信息
