### ISSUE TITLE
1.4.4-源码版本运行-无法获取弹幕

### ISSUE THREAD

**Issue by KagamiMiro** [xfgryujk/blivechat#24]
![image](https://user-images.githubusercontent.com/44522430/88617979-83b6fc00-d0ca-11ea-82ec-f82fc89ee6d9.png)
进入房间时报错 无法获取弹幕
blivedm.py使用的是大佬的项目里的最新版本

**Comment by KagamiMiro** [comment]
更换python3.7后修复

**Comment by xfgryujk** [comment]
查了下好像是tornado协程和aiohttp不兼容的问题
