### ISSUE TITLE
最低显示打赏价格设置0不显示辣条

### ISSUE THREAD

**Issue by xinnya** [xfgryujk/blivechat#28]
投喂辣条和小心心似乎没办法设置显示出来？

**Comment by xfgryujk** [comment]
免费礼物有什么显示的必要吗

**Comment by xinnya** [comment]
> 免费礼物有什么显示的必要吗

让萌新主播的弹幕看起来多一点

**Comment by xfgryujk** [comment]
想显示的话可以自己魔改
https://github.com/xfgryujk/blivechat/blob/cb150effbbd2833afc239823f0d745c8ab799604/api/chat.py#L174
https://github.com/xfgryujk/blivechat/blob/cb150effbbd2833afc239823f0d745c8ab799604/frontend/src/views/Room.vue#L162

**Comment by xinnya** [comment]
好了！谢谢大佬！不过显示价格有一毛钱，魔改成0了。
