### ISSUE TITLE
关于翻译问题

### ISSUE THREAD

**Issue by zzcabc** [xfgryujk/blivechat#33]
启动软件，出现腾讯翻译无法获取qtv参数，有道翻译处于冷却状态，b站自带翻译出现-400状态码，提示无效参数，有道和百度可能是我ip被暂时屏蔽，但是腾讯翻译换ip还是无法获取qtv参数

**Comment by xfgryujk** [comment]
腾讯翻译最近改了接口，如果急着用可以换成dev分支
