### ISSUE TITLE
从源码运行所有页面都是404

### ISSUE THREAD

**Issue by Redlnn** [xfgryujk/blivechat#35]
master分支没有进行修改，直接运行main.py，所有页面都是404，请问是什么原因？
<img width="1092" alt="Snipaste_2021-01-28_19-06-37" src="https://user-images.githubusercontent.com/41742767/106130135-f8fbaa80-619b-11eb-9e31-0651ecd1d41a.png">

**Comment by xfgryujk** [comment]
1. 编译前端（需要安装Node.js）：
```sh
cd frontend
npm i
npm run build
```

**Comment by Redlnn** [comment]
> 1. 编译前端（需要安装Node.js）：
> 
> ```shell
> cd frontend
> npm i
> npm run build
> ```

好的谢谢
