### ISSUE TITLE
你好，为什么我自建服务器或者本地docker运行了的房间URL还是使用sinacloud的地址呢？

### ISSUE THREAD

**Issue by longjun** [xfgryujk/blivechat#38]

**Comment by xfgryujk** [comment]
编辑配置去掉加载器：https://github.com/xfgryujk/blivechat#%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE

**Comment by longjun** [comment]
> 编辑配置去掉加载器：https://github.com/xfgryujk/blivechat#%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE

感觉你的回复，可以加联系方式请教和学习吗？

**Comment by xfgryujk** [comment]
> > 编辑配置去掉加载器：https://github.com/xfgryujk/blivechat#%E6%9C%8D%E5%8A%A1%E5%99%A8%E9%85%8D%E7%BD%AE
> 
> 感觉你的回复，可以加联系方式请教和学习吗？

我不私下加人，有问题可以在issue说
