### ISSUE TITLE
v1.1.3 启动闪退TAT

### ISSUE THREAD

**Issue by xiaoas** [xfgryujk/blivechat#4]
![image](https://user-images.githubusercontent.com/14904657/60878063-9ff2bb80-a271-11e9-9b27-63a9c493dc26.png)

**Comment by xiaoas** [comment]
另外，希望能加入动画效果😀

**Comment by xfgryujk** [comment]
你防火墙禁了80端口吧

**Comment by xfgryujk** [comment]
> 另外，希望能加入动画效果😀

这个在样式生成器里有

**Comment by xiaoas** [comment]
好的 谢谢😀
