### ISSUE TITLE
【PR request】我写了自定义弹幕表情包功能

### ISSUE THREAD

**Issue by DoodleBears** [xfgryujk/blivechat#42]
[DoodleBears/blivechat](https://github.com/DoodleBears/blivechat)
在README.md 有写简单的介绍
![实机演示图](https://github.com/DoodleBears/blivechat/blob/blivechat_doodlebear/screenshots/danmu_to_img.gif)

## 自定义弹幕表情包（弹幕转图片） —— 用正则表达式对弹幕内容做replace成img标签

1. 用正则表达式替换用户弹幕内容为html内容（在文字之间插入图片）
2. 从本地读取图片在`/frontend/dist/static`放入自己图片
3. 配置 `danmu_pic.json` 主要3个参数keyword、image、height，对应弹幕关键词，图片名称，图片高度

## 其他小改动
1. 最低金额设置可为float —— 设置为0时能显示金瓜子礼物，设置为0.1时候则仅显示金瓜子礼物（因为金瓜子礼物最低价格0.1RMB）
2. 区分舰队中的舰长、提督、总督，方便CSS做设定
3. 同时显示管理员和舰长的icon，样式采用舰队样式（判定舰队优先级高于管理员）

**Comment by xfgryujk** [comment]
1. 目前没有加图片的必要性
2. 用`v-html`我肯定不会同意的，非要做的话建议解析成数组，用`v-for`渲染
3. 代码风格和我的相差太大，例如用了`var`和`XMLHttpRequest`

**Comment by DoodleBears** [comment]
1. 了解了
2. 了解，之前用v-for写过直接特定弹幕转图片
但后来想让弹幕中的特定元素换成图片，一时想不到v-for怎么实现
3. 了解了

**Comment by xfgryujk** [comment]
解析出来的对象加个type属性，v-for里面v-if判断type，决定渲染什么元素

**Comment by DoodleBears** [comment]
好的，我去写一下，然后抱歉是因为我对vue和js都不是太了解

3. `var`和`XMLHttpRequest` 已经改为 `let` 和参考您用的 `axios` 来获取本地文件了

**Comment by DoodleBears** [comment]
### 用 v-for 和 v-if 实现
不知道对不对，我按你说的方案实作了一下。
```vue
<span v-for="(item, index) in contents" :key="index" >
        <img v-if="item.type == 'image'" :height="item.height" width="auto" :src="`/static/${item.content}`" />
        <span v-else>{{item.content}}</span>
</span>
```
您不愿意使用v-html是因为他的漏洞导致的危险性吗，抱歉我刚刚查了资料才知道这件事情。
感谢指点。

**Comment by xfgryujk** [comment]
是啊

**Comment by DoodleBears** [comment]
谢谢提醒。

如果目前没有加图片的必要性，我就关闭这个issue了
