### ISSUE TITLE
请问有办法只显示 sc 不显示弹幕吗？多谢！

### ISSUE THREAD

**Issue by valkjsaaa** [xfgryujk/blivechat#45]
As described in the title.

**Comment by DoodleBears** [comment]
> As described in the title.

我魔改的版本，如果能帮上忙
[DoodleBears/blivechat](https://github.com/DoodleBears/blivechat)

**Comment by xfgryujk** [comment]
首页不是有设置吗

**Comment by valkjsaaa** [comment]
> > As described in the title.
> 
> 我魔改的版本，如果能帮上忙
> [DoodleBears/blivechat](https://github.com/DoodleBears/blivechat)

太牛了，我试试

**Comment by valkjsaaa** [comment]
> 首页不是有设置吗

你说的是样式生成器吗，好像只能禁用除了 sc 的 banner 以外的所有信息？我想能够开启任意的一部分功能，比如只显示 sc 和 舰长，不显示礼物和弹幕

**Comment by DoodleBears** [comment]
> 首页不是有设置吗

可能是指`醒目留言(Super chat)`这一类别单独显示，不包含`新舰长`和 `礼物弹幕`

**Comment by valkjsaaa** [comment]
我暂时先用 DoodleBears 的版本啦，多谢！
