### ISSUE TITLE
功能建议:新弹幕显示在顶端

### ISSUE THREAD

**Issue by HowQi** [xfgryujk/blivechat#46]
目前似乎大多数弹幕显示工具弹幕似乎都是"新弹幕添加到末尾"的,在使用中,如果虚拟主播把自己的形象和弹幕显示放在同一侧,这样新弹幕就很有可能被遮挡,观众无法确认弹幕是否发送成功,如果看录播则会出现不知道主播正在与之互动的最新弹幕是哪一个,而价值相对下降的旧的弹幕则会被长时间顶上去,更容易看到。

因此我希望该项目能不能提供可选项,让新的弹幕显示在画面顶端,旧的弹幕向下运动? 这样更能节省直播界面空间,就算用什么挡住了弹幕显示的下半部分也几乎不会影响体验。

仔细观看了您提供的css设置和各种弹幕设置,没有看到类似的功能,希望能添加此使用功能 0v0

* 对不起手滑按到提交了,遂编辑之

**Comment by DoodleBears** [comment]
这个可以通过自己编写特定元素的`CSS`样式文件解决

新弹幕从上方出现，实际就是将呈现的弹幕的顺序颠倒
由123（从上到下为`旧弹幕`到`新弹幕`）—— 到321（从上到下为`新弹幕`到`旧弹幕`）

但是这样做的话，原先有的滑动效果（新弹幕进入：不是闪现插入而是滑入）就失效了。

如果想要保持新弹幕的进入效果，则需要修改blivechat的 [frontend/src/components/ChatRenderer/index.vue](https://github.com/xfgryujk/blivechat/blob/master/frontend/src/components/ChatRenderer/index.vue)文件

**Comment by HowQi** [comment]
> 这个可以通过自己编写特定元素的`CSS`样式文件解决
> 
> 新弹幕从上方出现，实际就是将呈现的弹幕的顺序颠倒
> 由123（从上到下为`旧弹幕`到`新弹幕`）—— 到321（从上到下为`新弹幕`到`旧弹幕`）
> ![](https://camo.githubusercontent.com/8c5c1d6cc090e320a18187d53a8336214d60adc60928340d2da62df3b51d2af9/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556835385a46777172396c6a7a746e6d514a2f67697068792e676966)
> 
> 但是这样做的话，原先有的滑动效果（新弹幕进入：不是闪现插入而是滑入）就失效了。
> 
> 如果想要保持新弹幕的进入效果，则需要修改blivechat的 [frontend/src/components/ChatRenderer/index.vue](https://github.com/xfgryujk/blivechat/blob/master/frontend/src/components/ChatRenderer/index.vue)文件

呜呜呜凭我浅薄的前端技能搞不懂该使用什么方式修改,方便的话能否给个提示,我该修改什么属性(或提供完整的代码参考?
另:我是不是应该在这个地方修改全部消息的属性?
```
/* Messages */
yt-live-chat-text-message-renderer #message,
yt-live-chat-text-message-renderer #message * {
  color: #ffffff !important;
  font-family: "Microsoft JhengHei", "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "\5FAE \8F6F \96C5 \9ED1 ", SimHei, Arial, sans-serif;
  font-size: 24px !important;
  line-height: 24px !important;
}
```

当然我仍然希望项目主为css生成器添加更多的功能——我是指这个反向弹幕的功能

**Comment by xfgryujk** [comment]
把浏览器源的高度设置小点就不会挡了
