### ISSUE TITLE
关于本地使用的 GUI 问题

### ISSUE THREAD

**Issue by sileence114** [xfgryujk/blivechat#48]
有打算搞GUI嘛？

没有的话我就用tk写个UI了。

TODO：
- 能最小化到托盘窗口，控制台窗口容易一不小心点了关掉。

**Comment by xfgryujk** [comment]
网页就是GUI

**Comment by sileence114** [comment]
我说的是双击 `blivechat.exe` 运行的那个

**Comment by xfgryujk** [comment]
你把main扩展名改成pyw再打包就没有控制台窗口了
