### ISSUE TITLE
样式生成小bug

### ISSUE THREAD

**Issue by xiaoas** [xfgryujk/blivechat#5]
在播放动画且字样消失后，即使在其他地方修改样式，消失的文本也不会再出现了。并且送礼super chat似乎没有正确的动画
希望预览动画时，消失动画能够提前发生。
命令行可以ctrl+c退出/托盘模式
还想问一下new member是什么意思 有人关注么0 0

**Comment by xfgryujk** [comment]
要点击播放动画才会再次出现
SC没有动画是设定
new member是有新舰长

**Comment by xiaoas** [comment]
0 0 SC 不会消失是设定么？不太明白实际会发生什么
”要点击播放动画才会再次出现“应该是个可以改进的地方吧

**Comment by xfgryujk** [comment]
因为SC本来就是要引起主播注意的东西
