### ISSUE TITLE
【功能增加】是否会考虑加入弹幕关键词抓取功能？

### ISSUE THREAD

**Issue by jay-mars** [xfgryujk/blivechat#52]
作者好，非常喜欢您的项目，我是一名B站主播。
我们直播间玩的是一种单机游戏，但是我们利用水友弹幕指挥自己国家，主播帮忙进行操作，然后开海打战。

是否可以增加一个，关键词抓起功能，然后高亮显示或者用什么方式来提现主播，以防看漏或者忘记操作。

比如： 弹幕1：罗马帝国 宣战 大秦。
弹幕2： 种地盟 议和 星球帝国。

这里的“宣战”和“议和” 就是关键词，也是主播需要去操作的地方。
作者是否愿意增加此功能呢~ 期待你的回信。

**Comment by xfgryujk** [comment]
不考虑出很小众的功能
