### ISSUE TITLE
增加上舰具体身份显示

### ISSUE THREAD

**Issue by Colerar** [xfgryujk/blivechat#54]
如题
建议提供舰长/提督/总督的分别显示。

**Comment by DoodleBears** [comment]
可以考虑这个版本：[https://github.com/DoodleBears/blivechat](https://github.com/DoodleBears/blivechat)

**Comment by Colerar** [comment]
那我也不急着 close 了，等这个 repo merge 吧。

**Comment by DoodleBears** [comment]
Repo 主之前有提过，说【这类功能建议自己魔改】

也就是说不会 merge

**Comment by Colerar** [comment]
OK
