### ISSUE TITLE
需要在css层增加官方表情和UP主大表情的id区分，或者提供禁止表情显示选项

### ISSUE THREAD

**Issue by merlin-kitsune** [xfgryujk/blivechat#60]
RT，官方表情大小合适会导致UP主大表情显示过小，UP主大表情显示合适会导致官方表情显示过大。能否从css层面进行区分，或者提供禁用开关

**Comment by xfgryujk** [comment]
表情太大有点喧宾夺主，参考国外的平台表情都是比文字稍大一点，现在的大小是合理的

**Comment by momokitsune** [comment]
你没明白我的意思。官方表情是长条的，且为文字大小做了适配不会因为和字差不多大缺少细节。而UP主大表情是主播自行找人约稿上传的，绝大多数没有根据文字大小做适配，所以在实际使用时候，需要增加大小来确保显示细节。主播的UP主大表情在后台上传的版本是162x162大小的。
在css层面，官方的表情和UP主大表情共用同一个id，导致我需要增加UP主大表情大小的时候，会连带将官方表情一并变大，导致观众发官方表情的时候占了过大面积。虽然可以指定height为想要的大小，把width设置为auto来缓解，但是仍然没法根本解决问题。内置的样式编辑器控制大小也是width而不是height。
所以我需要在css层面能区分官方表情和UP主大表情，避免因为调整UP主大表情到合适大小的时候导致官方表情显示过大。当然最好还是能禁用官方表情功能，直接输出文本，这样可以通过关键词来设置替换表情

**Comment by momokitsune** [comment]
另外还有几个CSS问题：
1. 如果最后一条弹幕是表情，会导致顶部的内容提前溢出，补发一条文字弹幕后又会显示正常。
2. 如果弹幕内容未设置为换行，且浏览器源宽度不足的情况下，发送表情弹幕会导致显示呈阶梯状错位。

我没有图床，github的issue也没办法上传图片，如果可能最好给一下其他联系方式谢谢

**Comment by swzsweet** [comment]
> 另外还有几个CSS问题：
> 
> 1. 如果最后一条弹幕是表情，会导致顶部的内容提前溢出，补发一条文字弹幕后又会显示正常。
> 2. 如果弹幕内容未设置为换行，且浏览器源宽度不足的情况下，发送表情弹幕会导致显示呈阶梯状错位。
> 
> 我没有图床，github的issue也没办法上传图片，如果可能最好给一下其他联系方式谢谢
github的issue可以直接粘贴图片的

**Comment by xfgryujk** [comment]
> 另外还有几个CSS问题：
> 
> 1. 如果最后一条弹幕是表情，会导致顶部的内容提前溢出，补发一条文字弹幕后又会显示正常。
> 2. 如果弹幕内容未设置为换行，且浏览器源宽度不足的情况下，发送表情弹幕会导致显示呈阶梯状错位。
> 
> 我没有图床，github的issue也没办法上传图片，如果可能最好给一下其他联系方式谢谢

你还是传截图吧
![QQ截图20220309184135](https://user-images.githubusercontent.com/8419596/157425814-325600bd-ba7e-44de-83fa-aa2a12125534.png)

**Comment by gin3715** [comment]
B站网页直播间的侧栏，通用表情的css class是`danmaku-content v-middle ts-dot-2 pointer emoticon`
而UP主自定义表情则是`danmaku-content v-middle ts-dot-2 pointer emoticon bulge`，多了一个`bulge`
自带的通用表情一般是2:1左右的aspect ratio，而UP主自定义表情则统一为1:1，为UP主表情额外添加一个css class（如`bulge`）可以方便更好地制定样式。
![QQ截图20220419124904](https://user-images.githubusercontent.com/17375889/164055063-870e81b1-2f93-41dc-a7c0-96fa1ab3a6e0.png)
![QQ截图20220419124919](https://user-images.githubusercontent.com/17375889/164055060-96c5372b-143e-4613-8551-4d47cba46783.png)

**Comment by gin3715** [comment]
@xfgryujk 
`DanmakuMessage.emoticon_options["bulge_display"]`的值`0`对应通用表情（无`bulge` class），值`1`对应UP主自定义表情（有`bulge` class）。
