### ISSUE TITLE
求支持斐讯N1 DOCKER

### ISSUE THREAD

**Issue by swzsweet** [xfgryujk/blivechat#61]

**Comment by xfgryujk** [comment]
都用docker了还有不支持的环境？

**Comment by shugen002** [comment]
![M~N_JO8M }~NI5UW C{G%S](https://user-images.githubusercontent.com/10257291/157246394-7168aa0d-642a-4c43-b5ff-902b7142d8cb.png)

跟了一下，docker镜像没有arm的，但是 Dockerfile都在项目里面了，自己build一下吧。

**Comment by swzsweet** [comment]
> ![M~N_JO8M }~NI5UW C{G%S](https://user-images.githubusercontent.com/10257291/157246394-7168aa0d-642a-4c43-b5ff-902b7142d8cb.png)
> 
> 跟一下，dockerfile都在里面了，自己build吧。

查了一圈，对我来说难度太大了
