### ISSUE TITLE
房间URL文本框内与按钮地址不一致

### ISSUE THREAD

**Issue by swzsweet** [xfgryujk/blivechat#64]
![image](https://user-images.githubusercontent.com/11248150/157399505-6694b77f-fe1f-4777-8013-16d07d542c58.png)
文本框：https://xfgryujk.sinacloud.net/blivechat/loader.html?url=http%3A%2F%2F192.168.123.2%3A12450%2Froom%2F8512200%3FminGiftPrice%3D7%26showDanmaku%3Dtrue%26showGift%3Dtrue%26showGiftName%3Dfalse%26mergeSimilarDanmaku%3Dfalse%26mergeGift%3Dtrue%26maxNumber%3D60%26blockGiftDanmaku%3Dtrue%26blockLevel%3D0%26blockNewbie%3Dfalse%26blockNotMobileVerified%3Dfalse%26blockKeywords%3D%26blockUsers%3D%26blockMedalLevel%3D0%26relayMessagesByServer%3Dfalse%26autoTranslate%3Dfalse%26giftUsernamePronunciation%3D%26emoticons%3D%255B%255D%26lang%3Dzh
打开房间按钮：http://192.168.123.2:12450/room/8512200?minGiftPrice=7&showDanmaku=true&showGift=true&showGiftName=false&mergeSimilarDanmaku=false&mergeGift=true&maxNumber=60&blockGiftDanmaku=true&blockLevel=0&blockNewbie=false&blockNotMobileVerified=false&blockKeywords=&blockUsers=&blockMedalLevel=0&relayMessagesByServer=false&autoTranslate=false&giftUsernamePronunciation=&emoticons=%5B%5D&lang=zh

**Comment by xfgryujk** [comment]
设计如此

**Comment by swzsweet** [comment]
> 设计如此

为啥会这样设计，复制的地址没有数据

**Comment by xfgryujk** [comment]
这是给本地使用用的，因为如果用原来的地址，先启动OBS再启动blivechat会加载失败，所以套了层加载器地址。可以在配置文件`data/config.ini`里禁用加载器地址
