### ISSUE TITLE
粉丝勋章显示

### ISSUE THREAD

**Issue by Itukii** [xfgryujk/blivechat#65]
想要一个粉丝勋章显示

**Comment by xfgryujk** [comment]
无法判断是不是粉丝

**Comment by xfgryujk** [comment]
> > 无法判断是不是粉丝
> 
> 我觉得他应该指的是粉丝团带等级的那个牌子。应该是在info[3]

这个没有显示的必要吧，我还写了个脚本去掉这个丑B牌子

**Comment by YoweTeam** [comment]
@xfgryujk 
 现在好多主播存留粉丝，粉丝勋章很重要。这块没有可选启用的选项？样式什么的，让启用的用户自己去写都行。看了一圈代码，数据结构有这方面的定义，没有获取过来。

**Comment by xfgryujk** [comment]
> [@xfgryujk](https://github.com/xfgryujk) 现在好多主播存留粉丝，粉丝勋章很重要。这块没有可选启用的选项？样式什么的，让启用的用户自己去写都行。看了一圈代码，数据结构有这方面的定义，没有获取过来。

https://github.com/xfgryujk/blivechat/discussions/257
