### ISSUE TITLE
仿微信样式的建议

### ISSUE THREAD

**Issue by czzzzaa** [xfgryujk/blivechat#68]
在微信样式中，弹幕聊天气泡还在用老式的圆润边框。这个边框和SC使用的圆角长方形在视觉上有极大的违和感。
希望作者可以考虑下把防微信模式的聊天气泡样式改为和SC一致的圆角长方形或者提供一种选项，允许用户自行切换。

**Comment by xfgryujk** [comment]
把字体调大就是圆角矩形了
