### ISSUE TITLE
要不要考虑加个css的手册来方便开发

### ISSUE THREAD

**Issue by Proanx** [xfgryujk/blivechat#73]
只通过页面生成css不能满足更高级的开发需要，但是手撸起来又有点抓瞎啊😭

**Comment by xfgryujk** [comment]
本项目与百度达成了合作，只需百度搜索“CSS教程”即可查看

**Comment by Proanx** [comment]
😅不是css的教程，是指页面最后成品dom的class、id、组件名列表，或者直接在css生成的页面标一下对应条目的class、id、组件名啥的也好

**Comment by xfgryujk** [comment]
Ｆ１２
