### ISSUE TITLE
支持deepl.com api翻译弹幕

### ISSUE THREAD

**Issue by aalberrty** [xfgryujk/blivechat#75]
因为deepl翻译相较于腾讯翻译&百度翻译会更加精准且人性化，所以如果可以在blivechat使用deepl翻译会更便于理解
希望可以考虑支持

**Comment by xfgryujk** [comment]
以前考虑过，官方文档并没有给出具体的频率限制，不清楚能否满足实时性。而且它的中日翻译没有吹的这么好，我还是优先选择没有中间语言的国产翻译服务
![deepl](https://user-images.githubusercontent.com/8419596/171036488-6b161cdb-f422-441b-99b2-6b9df57fb0c0.png)

**Comment by aalberrty** [comment]
了解了 感谢回复~
另外想问一下有没有捐赠渠道

**Comment by xfgryujk** [comment]
没有捐赠渠道
