### ISSUE TITLE
建议加入弹幕对齐设置

### ISSUE THREAD

**Issue by jjx874** [xfgryujk/blivechat#77]
默认弹幕都是左对齐，适合放在屏幕左侧。
希望加入选项，能够设置为右对齐和居中对齐。

选择弹幕自动消失，旧弹幕消失之后，新弹幕出现的位置仍然在旧弹幕下方，不会从初始位置出现，希望能调整为弹幕消失之后新弹幕从初始位置出现。

**Comment by xfgryujk** [comment]
自己改CSS
