### ISSUE TITLE
自定义字体似乎不行

### ISSUE THREAD

**Issue by MisakaMikoyo** [xfgryujk/blivechat#79]
使用说明中
●
样式生成器没有列出所有本地字体，但是可以手动输入本地字体

但是手动输入后会还原成之前的字体（列表中没有本地下载安装的字体）

请问怎么添加自定义字体

**Comment by DoodleBears** [comment]
1. 还原成之前的字体，如果是在手动输入「正确」的字体名称后，仍没有显示对应字体的话，可能是字体名称输入错误
2. 如果你用的是只熊的版本，应该在 [这里](https://github.com/DoodleBears/blivechat)提issue

**Comment by MisakaMikoyo** [comment]
感谢回复
已经找出问题
下载的自定义字体标题与内部标题不一致导致无法识别 
用软件更改了一下识别成功了
