### ISSUE TITLE
使用docker搭建的服务器，该如何指定host地址呢？

### ISSUE THREAD

**Issue by Csania-AM** [xfgryujk/blivechat#80]
默认应该是0.0.0.0，想设置成127.0.0.1，好像没有看到相关的变量设置

**Comment by xfgryujk** [comment]
那是docker的问题。你想搞反向代理就不要用端口映射，通过docker内部网络访问blivechat

**Comment by xfgryujk** [comment]
如果反向代理不在docker里，端口映射时要指定host `-p 127.0.0.1:12450:12450`
