### ISSUE TITLE
有没有可能 docker 镜像出个 arm 版本的～

### ISSUE THREAD

**Issue by Bryanthelol** [xfgryujk/blivechat#81]
我是 mac m1 芯片的电脑，目前运行容器会有如下图的情况：

<img width="971" alt="image" src="https://user-images.githubusercontent.com/22737787/183275674-8f86d00f-89de-4177-9c1e-b641f81f33c0.png">

期望出个 arm 版本的容器

**Comment by xfgryujk** [comment]
#62 这里有个别人构建的版本，我没有ARM测试环境所以不自己构建了

**Comment by Bryanthelol** [comment]
> #62 这里有个别人构建的版本，我没有ARM测试环境所以不自己构建了

好的，感谢，我去看看。
