### ISSUE TITLE
原有的api被反爬虫拦截

### ISSUE THREAD

**Issue by Xeler-ync** [xfgryujk/blivechat#84]
# 原有的api被反爬虫拦截
原api的返回值(已去除敏感数据)
```json
{
    "code": -401,
    "message": "非法访问",
    "ttl": 1,
    "data": {
        "ga_data": {
            "decisions": [
                "verify_captcha_level2"
            ],
            "risk_level": 1,
            "grisk_id": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "decision_ctx": {
                "buvid": "",
                "ip": "XXX.XXX.XXX.XXX",
                "mid": "0",
                "scene": "anti_crawler",
                "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36",
                "v_voucher": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
            }
        }
    }
}
```
不过这个还能用
https://api.bilibili.com/x/space/app/index

但是这个api返回了太多用不到的数据，可能会在大量请求新头像的时候比原来卡顿

**Comment by xfgryujk** [comment]
我发现加上当前的接口加上参数`jsonp=jsonp`还能用，不过是该增加几个接口防止被反爬了

**Comment by Xeler-ync** [comment]
> 我发现加上当前的接口加上参数`jsonp=jsonp`还能用，不过是该增加几个接口防止被反爬了

昨天晚上试了一下，好像反爬又消失惹 (っ °Д °;)っ
不需要修改原来的代码就能接着用

**Comment by xfgryujk** [comment]
又试了一下，感觉现在对不带cookie的请求是随机放行的，但是其他接口限制没这么严重

**Comment by Xeler-ync** [comment]
试了下，原本的接口在频率足够高的时候会被全ban
至于这个阈值是多少我没试出来，因为她已经不想理我惹

这是返回值
```json
{
    "code": -412,
    "message": "请求被拦截",
    "ttl": 1,
    "data": None
}
```
被ban之后，加上 ```jsonp=jsonp``` 也无法请求

不过似乎 https://api.bilibili.com/x/space/app/index 这个和原来的那个是分开的，原来的被ban的情况下，新的这个依旧可以使用

我还找到一个法子，就是请求手机端的个人主页
https://m.bilibili.com/space/{uid}

这里返回的数据里带上了用户的头像
这是xpath路径
```xpath
//*[@id="app"]/div/div[2]/div[2]/div[1]/img
```
以及我随便写的一个正则表达式
```regular
<img src="(https://i[0-9].hdslb.com/bfs/face/[0-9a-f]+.jpg)" class="bfs-img avatar" data-v-[0-9a-f]+>
```

伪装好headers之后，这个失效的概率可能会更低

PC端个人主页的头像来源就是请求咱原来的那个api了

**Comment by Xeler-ync** [comment]
又翻了一下手机端的个人主页，里面有一个 ```window.__INITIAL_STATE__``` 字典(js里面好像叫对象?)也存了头像的url
再随便写个正则
```re
"face":"https:\u002F\u002Fi[0-9].hdslb.com\u002Fbfs\u002Fface\u[0-9a-f]+.jpg",
```

**Comment by Xinrea** [comment]
只要带上 Cookie 就不会触发 401 了，Cookie 的内容不重要。例如：

```bash
curl 'https://api.bilibili.com/x/space/acc/info?mid=475210&jsonp=jsonp&platform=web' \
  -H 'cookie: random_cookie_content' \
  --compressed
```

**Comment by smdsbz** [comment]
现在好像又不行了，带上了那些 header 和 cookie 都不行（我甚至把自己的 SESSDATA 也丢进去了还是不行）。

**Comment by gin3715** [comment]
是否可以考虑定时使用高能榜API缓存头像。目前即便不送礼物，发弹幕的用户也会自动上榜。高能榜的API返回值同时包含uid和头像，可以提供一定程度上改善
`https://api.live.bilibili.com/xlive/general-interface/v1/rank/getOnlineGoldRank?ruid={主播UID}&roomId={房间ID}&page=1&pageSize=50`

**Comment by 123485k** [comment]
#90 要合并这个pr吗

**Comment by xfgryujk** [comment]
> #90 要合并这个pr吗

要合，这个基础上再改改

**Comment by ConfuciusSaid** [comment]
![image](https://user-images.githubusercontent.com/36434314/212529103-47745c8a-c69b-443a-ae8b-186901773ec5.png)
自己改了下，通过爬用户界面获取就可以了，原api不是超时就是被反爬拦截

**Comment by Yanstory** [comment]
> 自己改了下，通过爬用户界面获取就可以了，原api不是超时就是被反爬拦截

照着修了之后普通弹幕一直返回空头像，只有SC和礼物才能正常显示

**Comment by gin3715** [comment]
`https://line3-h5-mobile-api.biligame.com/game/center/h5/user/space/info?uid=xxxx&sdk_type=1`这个有人试过吗，游戏中心(`https://app.biligame.com/user_center?vmid=xxxx`)的API

**Comment by BAKAOLC** [comment]
```python

async def _do_get_avatar_url_from_web(user_id):
    try:
        async with utils.request.http_session.get(
            'https://api.bilibili.com/x/web-interface/card',
            params={
                'mid': user_id,
                'photo': '1',
                'jsonp': 'jsonp'
            }
        ) as r:
            if r.status != 200:
                logger.warning('Failed to fetch avatar: status=%d %s uid=%d', r.status, r.reason, user_id)
                if r.status == 412:
                    # 被B站ban了
                    global _last_fetch_banned_time
                    _last_fetch_banned_time = datetime.datetime.now()
                return None
            data = await r.json()
    except (aiohttp.ClientConnectionError, asyncio.TimeoutError):
        return None

    if data['code'] != 0:
        # 这里虽然失败但不会被ban一段时间
        logger.info('Failed to fetch avatar: code=%d %s uid=%d', data['code'], data['message'], user_id)
        return None

    avatar_url = process_avatar_url(data['data']['card']['face'])
    update_avatar_cache(user_id, avatar_url)
    return avatar_url
```

可以用这个获取个人信息的api进行头像的获取  
这个api是我经常用的，返回的信息比你们之前用的api还简洁一些  
调用这个api的时候，即使没设置cookie等参数的情况下依然可以正常工作  
而且并发配额较高，不需要等待那么久，具体并发限制你们可以自己测试  
据我自己的配置测试，我目前使用该api的所有发起了头像获取请求的调用都成功获取了头像信息  
少数头像不显示的情形的原因均为没有调用到这个函数所导致，因此这里可能需要你们进行进一步的问题筛查
