### ISSUE TITLE
[BUG Report]TencentTranslateFree init failed

### ISSUE THREAD

**Issue by Chenguoz** [xfgryujk/blivechat#88]
Windows10 程序运行时日志出现报错，弹幕功能正常
ERROR [services.translate]: TencentTranslateFree init failed: initial global variables not found
NoneType: None

**Comment by xfgryujk** [comment]
已知，以后翻译应该用官方接口了，不想修了

**Comment by ClementLevi** [comment]
笑死 用了这么久终于发现一个同样问题的
