### ISSUE TITLE
自建服务器的URL导入到OBS卡Loading

### ISSUE THREAD

**Issue by Chenguoz** [xfgryujk/blivechat#92]
使用docker镜像
`docker run --name blivechat -d -p 12450:12450 \
  --mount source=blivechat-data,target=/mnt/data \
  xfgryujk/blivechat:latest`
从首页点进入房间可以正常获取到房间弹幕，但是把URL导入到OBS就一直卡在Loading

**Comment by xfgryujk** [comment]
改一下配置，不使用加载器

**Comment by Chenguoz** [comment]
请问服务器配置路径`data/config.ini`是指宿主机的路径还是容器内部呀
`--mount source=blivechat-data,target=/mnt/data` 中的 `blivechat-data`对应的路径是在哪里...在当前目录没有找到QAQ

**Comment by xfgryujk** [comment]
你应该把docker中的`blivechat-data`卷挂载到宿主机的文件系统再修改。如果在容器内修改路径是`/mnt/data`

**Comment by Chenguoz** [comment]
感谢您的回复！我按照您给的方法成功解决了问题。
