### ISSUE TITLE
添加MonacoEditor

### ISSUE THREAD

**Issue by Debbl** [xfgryujk/blivechat#93]
作者，您好，我在用 el-input 中输入 CSS 时，有点不方便，所以我添加以一个 MonacoEditor 编辑器，您可以看一看吗？谢谢！https://github.com/Debbl/blivechat/commit/79d4871e7df5d8862bc961cb3f09a8d3572a58a3
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/61053131/200116430-57727440-c93b-44cc-a7a8-7b2fa2c3f21c.png">

**Comment by Debbl** [comment]
添加了窗口的自适应
https://github.com/Debbl/blivechat/commit/ba90145296e1fe3606a8f1d702cb9acd5ef91562

**Comment by Debbl** [comment]
> 作者，您好，我在用 el-input 中输入 CSS 时，有点不方便，所以我添加以一个 MonacoEditor 编辑器，您可以看一看吗？谢谢！[Debbl@79d4871](https://github.com/Debbl/blivechat/commit/79d4871e7df5d8862bc961cb3f09a8d3572a58a3) <img alt="image" width="1418" src="https://user-images.githubusercontent.com/61053131/200116430-57727440-c93b-44cc-a7a8-7b2fa2c3f21c.png">

添加了窗口的自适应
https://github.com/Debbl/blivechat/commit/ba90145296e1fe3606a8f1d702cb9acd5ef91562

**Comment by Debbl** [comment]
> > 作者，您好，我在用 el-input 中输入 CSS 时，有点不方便，所以我添加以一个 MonacoEditor 编辑器，您可以看一看吗？谢谢！[Debbl@79d4871](https://github.com/Debbl/blivechat/commit/79d4871e7df5d8862bc961cb3f09a8d3572a58a3) <img alt="image" width="1418" src="https://user-images.githubusercontent.com/61053131/200116430-57727440-c93b-44cc-a7a8-7b2fa2c3f21c.png">
> 
> 添加了窗口的自适应 [Debbl@ba90145](https://github.com/Debbl/blivechat/commit/ba90145296e1fe3606a8f1d702cb9acd5ef91562)

修复，overflow: hidden 溢出组件被遮挡
https://github.com/Debbl/blivechat/commit/7de9ec6e3166e6cbe077c8acdaa7438f88e53120

**Comment by xfgryujk** [comment]
你是要发PR吗

**Comment by Debbl** [comment]
> 你是要发PR吗

您要是允许我可以发一个 PR，谢谢！

**Comment by xfgryujk** [comment]
这个编辑起来会卡吗，我设想的用法是在其他编辑器编辑好后再粘贴到网页查看效果，因为直接编辑会经常更新CSS太卡了
还有打包体积会增加多少

**Comment by Debbl** [comment]
- 我在本地使用的是流畅的
- 是的，我使用了一段时间，就是感觉不是很方便，就想改进一下
- 下面是这个包体积的对比，因为我只引用了 CSS 语言所以不是特别的大，Gzip 后大概是 1.86MB
## 9ce1dd2: 更新教程截图

<img width="1430" alt="21" src="https://user-images.githubusercontent.com/61053131/200220644-2c80f201-6798-4122-86d7-ce68175627d6.png">
<img width="1430" alt="22" src="https://user-images.githubusercontent.com/61053131/200220658-cbca330d-deed-4e48-933a-a7404d3fafe4.png">
<img width="1430" alt="23" src="https://user-images.githubusercontent.com/61053131/200220660-1cfbe427-7d2c-4094-8f4a-edc3703826e0.png">


## 7de9ec6: 修复，固定布局溢出组件

<img width="1429" alt="11" src="https://user-images.githubusercontent.com/61053131/200220497-fd76aa5b-ac46-464f-a4a2-5039bd9ed475.png">
<img width="1429" alt="12" src="https://user-images.githubusercontent.com/61053131/200220501-97fd6ea7-71b2-42d2-89de-46881b96b160.png">
<img width="1429" alt="13" src="https://user-images.githubusercontent.com/61053131/200220506-b5861bfa-1fb7-4b4e-b320-9341edbd42ab.png">

**Comment by xfgryujk** [comment]
那还是算了，为了不常用的功能增加几倍体积不值得...

**Comment by Debbl** [comment]
> 那还是算了，为了不常用的功能增加几倍体积不值得...

行，麻烦您了
