### ISSUE TITLE
【建议】弹幕库新增进入直播间的进房信息记录

### ISSUE THREAD

**Issue by NakiriCr** [xfgryujk/blivechat#94]
B站直播间弹幕底下，如果有用户进入会短暂闪过【XXX进入直播间】这样的小提示，加到弹幕库的话能不那么容易漏看和错过进房信息 ~~ 

老哥看看如何 ~

**Comment by xfgryujk** [comment]
这种可以用官方的直播姬看，其实这个软件的定位主要是给观众看的而不是给主播看的

**Comment by NakiriCr** [comment]
> 这种可以用官方的直播姬看，其实这个软件的定位主要是给观众看的而不是给主播看的

好的捏，谢谢 ~
