### ISSUE TITLE
可以显示发送时间吗？

### ISSUE THREAD

**Issue by Yanstory** [xfgryujk/blivechat#98]
![image](https://user-images.githubusercontent.com/5153875/214082808-6d69a419-d808-44dc-825e-c2c7e4efbe5a.png)
（此图截自另一个网页弹幕姬）
例如这样的效果，我记得CSS是通用的，是因为什么原因去掉了吗？

**Comment by xfgryujk** [comment]
样式里面有设置

**Comment by Yanstory** [comment]
看到了，不过我是F12追的CSS😂也没想到就是CSS控制的

不过谢谢解答！
